/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import complementos.conexion;
import complementos.empleado;



/**
 *
 * @author ANDRES
 */
public class frm_principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_principal
     */
    empleado obj_empleado;
    public frm_principal() {
        initComponents();
        obj_empleado =new empleado();
        tbl_empleado.setModel(obj_empleado.leer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_codigo = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JTextField();
        txt_nacimiento = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_empleado = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        cb_puesto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(0, 204, 255));

        lbl_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_codigoActionPerformed(evt);
            }
        });

        txt_codigo.setText("codigo");

        txt_nombres.setText("nombres");

        lbl_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_nombresActionPerformed(evt);
            }
        });

        txt_apellidos.setText("apellidos");

        lbl_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_apellidosActionPerformed(evt);
            }
        });

        txt_direccion.setText("direccion");

        lbl_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_direccionActionPerformed(evt);
            }
        });

        txt_telefono.setText("telefono");

        lbl_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_telefonoActionPerformed(evt);
            }
        });

        txt_nacimiento.setText("fecha nacimiento");

        lbl_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_fechaActionPerformed(evt);
            }
        });

        jLabel8.setText("id");

        lbl_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_idActionPerformed(evt);
            }
        });

        tbl_empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_empleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_empleado);

        btn_agregar.setText("agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_actualizar.setText("actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        cb_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROGRAMADOR", "ANALISTA" }));
        cb_puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_puestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregar)
                .addGap(28, 28, 28)
                .addComponent(btn_actualizar)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codigo)
                    .addComponent(lbl_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombres)
                    .addComponent(lbl_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellidos)
                    .addComponent(lbl_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccion)
                    .addComponent(lbl_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefono)
                    .addComponent(lbl_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nacimiento)
                    .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_agregar)
                        .addComponent(btn_actualizar)
                        .addComponent(btn_eliminar))
                    .addComponent(cb_puesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_codigoActionPerformed

    private void lbl_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_nombresActionPerformed

    private void lbl_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_apellidosActionPerformed

    private void lbl_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_direccionActionPerformed

    private void lbl_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_telefonoActionPerformed

    private void lbl_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_fechaActionPerformed

    private void lbl_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_idActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
       /* obj_empleado = new empleado(0, this.lbl_codigo.getText(),this.lbl_nombres.getText(),this.lbl_apellidos.getText(),this.lbl_direccion.getText(),this.lbl_telefono.getText(),this.lbl_fecha.getText()this.cb_puesto.getAction(),0);
        tbl_empleado.setModel(obj_empleado.leer());*/

       /*obj_empleado = new empleado(0,  this.lbl_codigo.getText() , this.lbl_nombres.getText(), this.lbl_apellidos.getText(), this.lbl_direccion.getText(),this.lbl_telefono.getText(),this.lbl_fecha.getText(),this.cb_puesto.);
    obj_empleado.agregar();
    tbl_empleado.setModel(obj_empleado.leer());*/
       
       
        String puestoSeleccionado = this.cb_puesto.getSelectedItem().toString(); // Obtiene el nombre del puesto
    int id_puesto = obtenerIdPuesto(puestoSeleccionado); // Método que devuelve el id_puesto según el puesto seleccionado

    // Crear un nuevo objeto de empleado con los valores ingresados y el id_puesto
    obj_empleado = new empleado(
        0,  // ID del empleado (asumo que es autoincremental en la BD)
        this.lbl_codigo.getText(), 
        this.lbl_nombres.getText(), 
        this.lbl_apellidos.getText(), 
        this.lbl_direccion.getText(), 
        this.lbl_telefono.getText(), 
        this.lbl_fecha.getText(), 
        id_puesto  // ID del puesto obtenido del JComboBox
    );
    
    // Agregar el empleado a la base de datos
    obj_empleado.agregar();
    
    // Actualizar la tabla de empleados
    tbl_empleado.setModel(obj_empleado.leer());
        
       
       
      // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarActionPerformed
     public void selec_datos (){
    int fila = this.tbl_empleado.getSelectedRow();
        lbl_id.setText(this.tbl_empleado.getValueAt(fila, 0).toString());
        this.lbl_codigo.setText(this.tbl_empleado.getValueAt(fila, 1).toString());
        this.lbl_nombres.setText(this.tbl_empleado.getValueAt(fila, 2).toString());
        this.lbl_apellidos.setText(this.tbl_empleado.getValueAt(fila, 3).toString());
        this.lbl_direccion.setText(this.tbl_empleado.getValueAt(fila, 4).toString());
        this.lbl_telefono.setText(this.tbl_empleado.getValueAt(fila, 5).toString());
        this.lbl_fecha.setText(this.tbl_empleado.getValueAt(fila, 6).toString());
    
        String puesto = this.tbl_empleado.getValueAt(fila, 7).toString();
         this.cb_puesto.setSelectedItem(puesto);
    
    }
    
    private void tbl_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_empleadoMouseClicked
        // TODO add your handling code here:
        selec_datos();
    }//GEN-LAST:event_tbl_empleadoMouseClicked

    private void cb_puestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_puestoActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_cb_puestoActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed

obj_empleado = new empleado(
        Integer.parseInt(lbl_id.getText()), // ID del empleado a actualizar
        lbl_codigo.getText(),
        lbl_nombres.getText(),
        lbl_apellidos.getText(),
        lbl_direccion.getText(),
        lbl_telefono.getText(),
        lbl_fecha.getText(),
        cb_puesto.getSelectedIndex() // ID del puesto seleccionado en el JComboBox
    );
    
    // Llamar al método para actualizar el empleado
    obj_empleado.actualizar();

    // Actualizar la tabla de empleados
    tbl_empleado.setModel(obj_empleado.leer());
}



        // TODO add your handling code here:
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed


int idEmpleado = Integer.parseInt(lbl_id.getText());
    
    // Crear el objeto empleado con el ID y llamar al método eliminar
    obj_empleado = new empleado(idEmpleado);
    obj_empleado.eliminar();

    // Actualizar la tabla de empleados
    tbl_empleado.setModel(obj_empleado.leer());


// TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JComboBox<String> cb_puesto;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lbl_apellidos;
    private javax.swing.JTextField lbl_codigo;
    private javax.swing.JTextField lbl_direccion;
    private javax.swing.JTextField lbl_fecha;
    private javax.swing.JTextField lbl_id;
    private javax.swing.JTextField lbl_nombres;
    private javax.swing.JTextField lbl_telefono;
    private javax.swing.JTable tbl_empleado;
    private javax.swing.JLabel txt_apellidos;
    private javax.swing.JLabel txt_codigo;
    private javax.swing.JLabel txt_direccion;
    private javax.swing.JLabel txt_nacimiento;
    private javax.swing.JLabel txt_nombres;
    private javax.swing.JLabel txt_telefono;
    // End of variables declaration//GEN-END:variables
}
